name: Check Docker Compose development environment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: curl -s --retry 10 --retry-connrefused http://localhost:8082/